### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### GET all missions
GET http://localhost:9000/mission

### POST mission
POST http://localhost:9000/mission
Content-Type: application/json

{
    "missionName": "Test Mission 2",
    "text": "Dies ist eine Test Mission"
}

###PUT Request
PUT http://localhost:9000/mission
Content-Type: application/json

{
  "id": "cc2f031a-1764-426c-8a1f-deb4abcd67ce",
  "missionName": "Test Mission update",
  "text": "Dies ist eine Test Mission mit update"
}

### PUT Request mit platoon
PUT http://localhost:9000/mission
Content-Type: application/json

{
  "id": "cc2f031a-1764-426c-8a1f-deb4abcd67ce",
  "missionName": "Update mission",
  "text": "Update Mission mit platoon",
  "platoon": {
    "id": "3d2c0852-ce46-4c0a-a863-e11a74464bb4",
    "platoonname": "test",
    "leader": "test",
    "missionModels": [],
    "timeActiveMission": ""
  }
}